<a href="https://colab.research.google.com/github/170830pushpa/python_training/blob/main/Asignment_X_Numpy_pushpa_7thsem_cs170830.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                      ***Assignment*** 

1) Find the inverse of the following matrices
  A =[[1,2,3][55,66,77]]       B=[[1,2,3][55,66,77][6,7,12]]      C=[1,2,3,8][5,6,7,5],[6,7,12,12][11,12,13,20]]

In [1]:
import numpy as np
A=np.array([[1,2,3],
            [55,66,77]])
B=np.array([[1,2,3],
            [55,66,77],
            [6,7,12]])
C=np.array([[1,2,3,8],
            [5,6,7,5],
            [6,7,12,12],
            [11,12,13,20]])

def invertornot(A):
  if len(A)==len(A[0]):
    if np.linalg.det(A)!=0:
      return True
    else:
      return False
  else:
    return False 
print("\n================================================")
if invertornot(A)==True:
  print("Inverse of A is:\r")
  print(np.linalg.inv(A))
else:
  print("Matrx is not invertible.")
print("\n=================================================")
if invertornot(B)==True:
  print("Inverse of B is:\r")
  print(np.linalg.inv(B))
else:
    print("Matrx is not invertible.")
print("\n====================================================")
if invertornot(C)==True:
  print("Inverse of C is:\r")
  print(np.linalg.inv(C))
else:
    print("Matrx is not invertible.")


Matrx is not invertible.

Inverse of B is:
[[-1.4375      0.01704545  0.25      ]
 [ 1.125       0.03409091 -0.5       ]
 [ 0.0625     -0.02840909  0.25      ]]

Inverse of C is:
[[-0.85576923 -0.78205128  0.25        0.38782051]
 [ 0.75        1.         -0.5        -0.25      ]
 [-0.08653846 -0.06410256  0.25       -0.09935897]
 [ 0.07692308 -0.12820513 -0.          0.05128205]]


2) Find the values of x1, x2 and x3       
5x1 + 4 x2 + 3 x3 = 5                
6x1 - 8x2   + 7x3 = 15           
X1   - x2     +10x3 = 25 


In [2]:
A=np.array([[5,4,3],
   [6,8,7],
    [1,-1,10]])
B=np.array([5,15,25])
#AX=B
#X=(inverse of A)*B
print("\n================================================")
if invertornot(A)==True:
  np.linalg.inv(A)
  re=np.dot((np.linalg.inv(A)),B)
  x1=re[0]
  x2=re[1]
  x3=re[2]
  print("x1= {}\nx2= {}\nx3= {}".format(x1,x2,x3))
else:
  print("\nError:    Matrix is not invertible")




x1= -0.6077348066298343
x2= 0.08287292817679544
x3= 2.569060773480663


3) Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [3]:
Zero=np.zeros(10)
one=np.ones(10)
five=np.ones(10)*5
print("\n================================================")
print(Zero)
print("\n================================================")
print(one)
print("\n================================================")
print(five)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


4) Write a NumPy program to compute the eigenvalues and eigenvectors of a given square array.     B=[[1,2,3],[55,66,7],[6,7,12],]

In [4]:
import numpy as np
B=np.array([[1,2,3],
    [55,66,7],
    [6,7,12]])
print("Eigen vector and eigen values of B matrix  are \r")
print(np.linalg.eig(B))


Eigen vector and eigen values of B matrix  are 
(array([68.81905127, -0.70229368, 10.88324241]), array([[ 0.03480353,  0.77221412,  0.21267997],
       [ 0.99144253, -0.6351919 , -0.32907749],
       [ 0.12581905, -0.01471714,  0.92004089]]))


5) Write a NumPy program to generate five random numbers from the normal distribution.

In [5]:
print("five random numbers from the normal distribution are\r")
print(np.random.normal(size=5))

five random numbers from the normal distribution are
[ 0.5612019   1.89956997 -0.12249628 -0.67146563 -0.81272307]


6) Write a NumPy program to generate six random integers between 10 and 30.

In [6]:
print(" six random integers between 10 and 30 are\r")
print(np.random.randint(low=10,high=30,size=6))

 six random integers between 10 and 30 are
[13 12 16 22 24 22]


7) Write a NumPy program to create a 3x3x3 array with random values.

In [7]:
A=np.random.random((3,3,3))
print("A 3x3x3 array with random values =\n")
print(A)

A 3x3x3 array with random values =

[[[0.48348816 0.90169996 0.94921784]
  [0.7976582  0.05368493 0.0250044 ]
  [0.19065021 0.39303276 0.7364894 ]]

 [[0.44353613 0.34306593 0.61538963]
  [0.91634418 0.12044165 0.2556162 ]
  [0.73235198 0.046089   0.34343216]]

 [[0.03246868 0.295643   0.62595383]
  [0.09551582 0.71169679 0.15402826]
  [0.89068735 0.3512237  0.5411597 ]]]


8) Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [8]:
A=np.random.random((5,5))
print("A 5*5 array with random values =\n")
print(A)
print("======================================================\n")
max=np.amax(A)
print("Maximum value in above matrix is    ",max)

A 5*5 array with random values =

[[0.5178659  0.55808825 0.0486964  0.28278184 0.6794651 ]
 [0.71269424 0.70985814 0.36408651 0.33675198 0.7988078 ]
 [0.39164864 0.77527008 0.17587269 0.76251437 0.94329545]
 [0.07582608 0.48916235 0.42799381 0.35684081 0.37108917]
 [0.59537959 0.85975489 0.72822424 0.87279348 0.9343986 ]]

Maximum value in above matrix is     0.9432954517436761


9) Write a NumPy program to normalize a 3x3 random matrix.

In [9]:
A=np.random.random((3,3))
print("A 3*3 random matrix is \n")
print(A)
print("===============================")
print("Normalized matrix is \n",(A/(np.linalg.norm(A))))

A 3*3 random matrix is 

[[0.9833543  0.99186596 0.72419963]
 [0.56714167 0.39669617 0.38616644]
 [0.61736616 0.26360439 0.44823321]]
Normalized matrix is 
 [[0.50746836 0.51186088 0.37372939]
 [0.29267829 0.20471844 0.19928448]
 [0.31859707 0.13603529 0.23131457]]


10) Write a NumPy program to create a random vector of size 10 and sort it

In [10]:
A=np.random.random(10)
print("Random vector of size 10 is \n")
print(A)
print("================================================================\n")
A.sort()
print("Sorted vector is\n",A)


Random vector of size 10 is 

[0.00159429 0.90855721 0.01947294 0.44909592 0.3790225  0.90920007
 0.55687582 0.01553883 0.10163561 0.06885   ]

Sorted vector is
 [0.00159429 0.01553883 0.01947294 0.06885    0.10163561 0.3790225
 0.44909592 0.55687582 0.90855721 0.90920007]


11) Write a NumPy program to check if two random arrays are equal or not

In [11]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
print("A=\r")
print(A)
print("B=\r")
print(B)
print("=========================================")
if np.allclose(A,B)==True:
  print("A and B are equal.")
else:
  print("A and B are not equal.")

A=
[1 0 1 0 1]
B=
[0 0 1 0 1]
A and B are not equal.


12) Write a NumPy program to create a random vector of size 15 and replace the maximum value by -1

In [12]:
A=np.random.random(15)
print("A random vector of size 15 is \n")
print(A)
max=np.amax(A)
max_pos=np.argmax(A)
print("=========================================================================\n")
print("Maximum value in vector is  ",max)
print("=========================================================================\n")
A[max_pos]=-1
print("Vector after repalcing max value by -1 is \n")
print("=========================================================================\n")
print(A)

A random vector of size 15 is 

[0.40544603 0.8440403  0.13661304 0.62966488 0.5447298  0.2147684
 0.79778589 0.09555905 0.85201912 0.98974887 0.91309505 0.33244501
 0.79216983 0.78719228 0.97725787]

Maximum value in vector is   0.989748868087872

Vector after repalcing max value by -1 is 


[ 0.40544603  0.8440403   0.13661304  0.62966488  0.5447298   0.2147684
  0.79778589  0.09555905  0.85201912 -1.          0.91309505  0.33244501
  0.79216983  0.78719228  0.97725787]


13) Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on a flattened array.    A=[[1,2],[11,12]]

In [13]:
A=np.array([[1,2],
            [11,12]])
print("=====================================\n")
print("Sordted along first axis:\n")
print(np.sort(A,axis=0))
print("=====================================\n")
print("Sordted along last axis:\n")
print(np.sort(A))
print("=====================================\n")
print("Sordted along first axis:\n")
print(np.sort(A,axis=None))


Sordted along first axis:

[[ 1  2]
 [11 12]]

Sordted along last axis:

[[ 1  2]
 [11 12]]

Sordted along first axis:

[ 1  2 11 12]


14) Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describe the sort order by multiple columns and the sorted data.

         id=[123,126,140,153]        height=[145,155,165,153]

In [14]:
id=np.array([123,126,140,153])
height=np.array([145,155,165,153])
i=np.lexsort((id,height))
print("Data is sorted in followind order:\n")

print(i)
print("===========================================\n")
print("IN sorted order:\n")
print("===========================================\n")
print("    ID                       Height\n")
print("=============================================\n")
for j in i:
  print("\n  ",id[j],"                  ",height[j])

Data is sorted in followind order:

[0 3 1 2]

IN sorted order:


    ID                       Height



   123                    145

   153                    153

   126                    155

   140                    165


15) Write a NumPy program to get the indices of the sorted elements of a given array.
X = [1023 5202 6230 1671 1682 5241 4532]


In [15]:
X = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
i=np.argsort(X)
print("Indices of sorted elements in given array is \n")
print(i)
print("===============================")
print("Sorted array is\n")
print(np.sort(X))

Indices of sorted elements in given array is 

[0 3 4 6 1 5 2]
Sorted array is

[1023 1671 1682 4532 5202 5241 6230]


16) Write a NumPy program to sort a given complex array using the real part first, then the imaginary part.
Y = [(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)]


In [16]:
Y =np.array([(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)])
print("Before sorting:\n")
print(Y)
print("====================\n")
print("After sorting:\n")
print(np.sort_complex(Y))


Before sorting:

[1.+2.j 3.-1.j 3.-2.j 4.-3.j 3.+5.j]

After sorting:

[1.+2.j 3.-2.j 3.-1.j 3.+5.j 4.-3.j]


17)  Multiply AXB   


        A=  [[1,2],[11,22],[12,15]]
        B=[[1,2,3][11,12,13]]

In [17]:
  A= np.array([ [1,2],
                [11,22],
                [12,15]])
  B=np.array([[1,2,3],
              [11,12,13]])
  C=A.dot(B)
print("AxB=\r")
print(C)

AxB=
[[ 23  26  29]
 [253 286 319]
 [177 204 231]]


18) Write a NumPy program to compute e^x, element-wise of a given array.
A = [1,5,6,9]


In [18]:
A=np.array([1,5,6,9])
print("Element-wise e^x of given array A is:")
print(np.exp(A))

Element-wise e^x of given array A is:
[2.71828183e+00 1.48413159e+02 4.03428793e+02 8.10308393e+03]


19) Write a NumPy program to compute natural, base 10, and base 2 logarithms for all elements in a given array.
A = [1,2.5,56,19]


In [19]:
A=np.array([1,2.5,56,19])
print("\nNatural logarithms for all elements in a given array:\n")
print("===========================================================\n")
print(np.log(A))
print("\nBase 10 logarithms for all elements in a given array:\n")
print("===========================================================\n")
print(np.log10(A))
print("\nNatural logarithms for all elements in a given array:\n")
print("===========================================================\n")
print(np.log2(A))


Natural logarithms for all elements in a given array:


[0.         0.91629073 4.02535169 2.94443898]

Base 10 logarithms for all elements in a given array:


[0.         0.39794001 1.74818803 1.2787536 ]

Natural logarithms for all elements in a given array:


[0.         1.32192809 5.80735492 4.24792751]


20) Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis.
A = [[ 0 1 2 3 4 5]
[ 6 7 8 9 10 11]]


In [20]:
A=np.array([[0,1,2,3,4,5],
            [6,7,8,9,10,11]])
max=np.amax(A,axis=1)
min=np.amin(A,axis=1)
print("difference between the maximum and the minimum values of a given array along the second axis\n")
print(max-min)

difference between the maximum and the minimum values of a given array along the second axis

[5 5]


21) Write a NumPy program to compute the median of a flattened given array.
B =[[ 0 1 2 3 4 5]
[ 6 7 8 9 10 11]]


In [21]:
B=np.array([[0,1,2,3,4,5],
            [6,7,8,9,10,11]])
print("Median of flattened goven array is ")
print(np.median(B,axis=None))

Median of flattened goven array is 
5.5


22) Write a NumPy program to compute cross-correlation of two given arrays.

A = [0 1 3]
B = [2 4 5]


In [22]:
A=np.array([0,1,3])
B=np.array([2,4,5])
print(" cross-correlation of two given arrays is")
print(np.cov(A,B))

 cross-correlation of two given arrays is
[[2.33333333 2.16666667]
 [2.16666667 2.33333333]]


23) Write a Python program to count the number of occurrences of each value in a given array of non-negative integers.
A = [0, 1, 6, 1, 4, 1, 2, 2, 7]


In [23]:
 A = np.array([0, 1, 6, 1, 4, 1, 2, 2, 7])
 count=np.bincount(A)
 print(" number of occurrences of each value in a given array of non-negative integers is:\n")
 print("=========================================================================================\n")
 print("   number       occurrence-count\n")
 print("-----------------------------------")
 for i in A:
   print("    ",A[i],"              ",count[i])
   print("-----------------------------------")

 number of occurrences of each value in a given array of non-negative integers is:


   number       occurrence-count

-----------------------------------
     0                1
-----------------------------------
     1                3
-----------------------------------
     2                1
-----------------------------------
     1                3
-----------------------------------
     4                1
-----------------------------------
     1                3
-----------------------------------
     6                2
-----------------------------------
     6                2
-----------------------------------
     2                1
-----------------------------------


24) Write a NumPy program to display all the dates for the month of May, 2021.

In [24]:
print("                            May, 2021")
print("=================================================================")
print(np.arange('2017-05', '2017-06', dtype='datetime64[D]'))
print("=================================================================")

                            May, 2021
['2017-05-01' '2017-05-02' '2017-05-03' '2017-05-04' '2017-05-05'
 '2017-05-06' '2017-05-07' '2017-05-08' '2017-05-09' '2017-05-10'
 '2017-05-11' '2017-05-12' '2017-05-13' '2017-05-14' '2017-05-15'
 '2017-05-16' '2017-05-17' '2017-05-18' '2017-05-19' '2017-05-20'
 '2017-05-21' '2017-05-22' '2017-05-23' '2017-05-24' '2017-05-25'
 '2017-05-26' '2017-05-27' '2017-05-28' '2017-05-29' '2017-05-30'
 '2017-05-31']


25) Write a NumPy program to concatenate element-wise two arrays of string.
A = ['Python' 'PHP']
B = [' Java' ' C++']


In [25]:
A = np.array(['Python', 'PHP'])
B = np.array([' Java' ,' C++'])
print(np.char.add(A,B))

['Python Java' 'PHP C++']
